version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgresdb
    restart: on-failure
    environment:
      POSTGRES_DB: cookease-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    networks:
      - service-network
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - service-network
  cookease-server:
    image: ${DOCKER_REGISTRY-}cookease-server
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
      - ASPNETCORE_HTTP_PORTS=80
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - service-network
  cookease-client:
    image: ${DOCKER_REGISTRY-}cookease-client
    build:
      context: ./Client
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=http://cookease-server:80/
      - REACT_APP_CLIENT_PORT=80
    ports:
      - "5001:80"
    networks:
      - service-network
networks:
  service-network:
    name: main-services-network
    driver: bridge